{
 "title": "SLO",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Task Success SLO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (job, instance) (rate(flask_http_request_total{method=\"POST\", status=~\"2..\"}[5m]))\r\n/\r\nsum by (job, instance) (rate(flask_http_request_total{method=\"POST\"}[5m]))\r\n* 100\r\n",
     "legendFormat": "Task Success (%)"
    }
   ]
  },
  {
   "title": "Error Rate SLO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(flask_http_request_total{status=~\"4..|5..\"}[5m]))\r\n  /\r\n  sum(rate(flask_http_request_total[5m]))\r\n) * 100\r\n",
     "legendFormat": "Error Rate (%)"
    }
   ]
  },
  {
   "title": "Latency SLO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_bucket{le=\"0.025\"}[5m]))\r\n/\r\nsum(rate(flask_http_request_duration_seconds_count[5m]))\r\n* 100\r\n",
     "legendFormat": "<= 25ms"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_bucket{le=\"0.5\"}[5m]))\r\n/\r\nsum(rate(flask_http_request_duration_seconds_count[5m]))\r\n* 100\r\n",
     "legendFormat": "<= 50ms"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_bucket{le=\"0.05\"}[5m]))\r\n/\r\nsum(rate(flask_http_request_duration_seconds_count[5m]))\r\n* 100\r\n",
     "legendFormat": "<= 500 ms"
    }
   ]
  },
  {
   "title": "Availability SLO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(flask_http_request_total{status=~\"2..\"}[1h]))\r\n  /\r\n  sum(rate(flask_http_request_total[1h]))\r\n) * 100\r\n",
     "legendFormat": "availability (%)"
    }
   ]
  }
 ]
}