{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Task-level SLI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(create_task_total[10m])",
     "legendFormat": "{{job}} task rate"
    }
   ]
  },
  {
   "title": "Availability SLI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(flask_http_request_total{status=~\"2..\"}[5m]))\r\n  /\r\n  sum(rate(flask_http_request_total[5m]))\r\n) * 100\r\n",
     "legendFormat": "Availability (2..)"
    }
   ]
  },
  {
   "title": "Rate of client/server errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{status=~\"4..|5..\"}[5m]))\r\n",
     "legendFormat": "Errors (4../5..)"
    }
   ]
  },
  {
   "title": "Latency SLI",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum[5m])\r\n/\r\nrate(flask_http_request_duration_seconds_count[5m])",
     "legendFormat": "{{endpoint}} ({{method}})"
    }
   ]
  }
 ]
}