name: Backend CI/CD

on:
  push:
    branches:
      - main  # Триггер при пуше в main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (Backend)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest ./flask
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest
